name: Build Finance Video

on:
  workflow_dispatch:   # lets you run manually from GitHub
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 UTC (adjust later)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run video build script
        env:
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
        run: python scripts/make_video.py

      - name: Upload result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: finance-video
          path: final_video.mp4
